// Postman Application Configuration
// Generated by `postman application init`
//
// Docs: https://learning.postman.com/docs/postman-cli/postman-cli-options/

module.exports = {
    // The command to run before analysis (e.g. your test suite).
    command: 'npm --prefix e2e test',

    // Targets define which collections and environment to use for analysis.
    // Select a target at runtime with: postman application test --target <name>
    targets: {
         default: {
             environment: 'Localhost',
             collections: [
                 'PublicApi Endpoints',
                 'Storefront UI',
         ],
        },

        // Example: a beta/staging target
        // beta: {
        //     environment: 'Staging',
        //     collections: [
        //         'My Collection',
        //     ],
        // },

        // Example: a production target
        // production: {
        //     environment: 'Production',
        //     collections: [
        //         'My Collection',
        //     ],
        // },
    },

    // Filters exclude matching network requests from analysis.
    // A request is dropped if it matches any rule below.
    //
    // We match two collections: the REST API on localhost:5200
    // ("PublicApi Endpoints") and the Web storefront pages/form posts on
    // localhost:5106 ("Storefront UI"). The only genuinely irrelevant traffic
    // is static assets (CSS/JS/images/fonts) served by the storefront, so we
    // drop just those and let the real HTML/API requests through to matching.
    filters: {
        urlPatterns: [
            '\\.css$', '\\.js$',
            '\\.png$', '\\.jpg$', '\\.jpeg$', '\\.svg$', '\\.ico$', '\\.gif$',
            '\\.woff2?$', '\\.ttf$', '\\.eot$',
        ],
        methods: [],
        headers: {},
    },

    // Transformers rewrite proxied requests back to their real upstream URLs
    // so that captured traffic can be matched against your Postman collections.
    //
    // When your app routes API calls through a gateway or proxy, the captured
    // URL is the gateway URL — not the real service URL. Each transformer entry
    // lets you reverse that mapping:
    //
    //   url              – prefix string or RegExp to match the transformer URL.
    //   transformRequest  – receives the raw request body and returns
    //                       { url, method } pointing to the real service.
    //   transformResponse – (optional) unwraps the transformer response envelope
    //                       so assertions see the real payload.
    //
    // transformers: [
    //     {
    //         url: 'https://api-gateway.example.com/proxy',
    //
    //         transformRequest (body) {
    //             var parsed = typeof body === 'string'
    //                 ? JSON.parse(body) : (body || {});
    //
    //             return {
    //                 url: 'https://' + parsed.service + '.internal.example.com' + parsed.path,
    //                 method: (parsed.method || 'GET').toUpperCase(),
    //             };
    //         },
    //
    //         transformResponse (response) {
    //             if (response && typeof response === 'object' && 'data' in response) {
    //                 return response.data;
    //             }
    //
    //             return response;
    //         },
    //     },
    // ],
};
